# PART1: TF

## SETUP

In [1]:
import tensorflow as tf

In [2]:
# !pip install mitdeeplearning --quiet
import mitdeeplearning as mdl
import numpy as np
import matplotlib.pyplot as plt

## 1.1

In [13]:
# 0 d
sport = tf.constant("Tennis", tf.string)
number = tf.constant(1.41421356237, tf.float64)

print("`sport` is a {}-d Tensor".format(tf.rank(sport).numpy()))
print("`number` is a {}-d Tensor".format(tf.rank(number).numpy()))

`sport` is a 0-d Tensor
`number` is a 0-d Tensor


In [19]:
# 1 d
sports = tf.constant(["Tennis", "Basketball"], tf.string)
numbers = tf.constant([3.141592, 1.424213, 2.71821], tf.float64)

print("`sports` is a {}-d Tensor with shape: {}".format(tf.rank(sports).numpy(), tf.shape(sports)))
print("`numbers` is a {}-d Tensor with shape: {}".format(tf.rank(numbers).numpy(), tf.shape(numbers)))

`sports` is a 1-d Tensor with shape: [2]
`numbers` is a 1-d Tensor with shape: [3]


In [23]:
### Defining higher-order Tensors ###

"""TODO: Define a 2-d Tensor"""
matrix = tf.constant([[1, 2], [3, 2]])  # TODO

assert isinstance(matrix, tf.Tensor), "matrix must be a tf Tensor object"
assert tf.rank(matrix).numpy() == 2

In [29]:
'''TODO: Define a 4-d Tensor.'''
# Use tf.zeros to initialize a 4-d Tensor of zeros with size 10 x 256 x 256 x 3.
#   You can think of this as 10 images where each image is RGB 256 x 256.
images = tf.zeros([10, 256, 256, 3])  # TODO

assert isinstance(images, tf.Tensor), "matrix must be a tf Tensor object"
assert tf.rank(images).numpy() == 4, "matrix must be of rank 4"
assert tf.shape(images).numpy().tolist() == [
    10, 256, 256, 3], "matrix is incorrect shape"

In [36]:
matrix

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 2],
       [2, 3]], dtype=int32)>

## 1.2

In [41]:
a = tf.constant(15)
b = tf.constant(61)

tf.add(a, b)

<tf.Tensor: shape=(), dtype=int32, numpy=76>

In [55]:
### Defining Tensor computations ###


# Construct a simple computation function
def func(a, b):
    """TODO: Define the operation for c, d, e (use tf.add, tf.subtract, tf.multiply)."""
    print(f"a = {a}, b = {b}")
    c = tf.add(a, b)
    print(f"c = a+b = {a}+{b}={c}")
    d = tf.subtract(b, 1)
    print(f"d = b-1 = {b}-1 = {d}")
    e = tf.multiply(c, d)
    print(f"e = c*d = {e}")
    return e

In [56]:
# Consider example values for a,b
a, b = 1.5, 2.5
# Execute the computation
e_out = func(a, b)
print(e_out)

a = 1.5, b = 2.5
c = a+b = 1.5+2.5=4.0
d = b-1 = 2.5-1 = 1.5
e = c*d = 6.0
tf.Tensor(6.0, shape=(), dtype=float32)


## 1.3